services:
  mariadb:
    image: mariadb:10.6
    container_name: flansa-mariadb-working
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: frappe
    ports:
      - "3308:3306"
    networks:
      - frappe-network

  redis:
    image: redis:7-alpine
    container_name: flansa-redis-working
    ports:
      - "6382:6379"
    networks:
      - frappe-network

  frappe:
    image: frappe/bench:latest
    container_name: flansa-frappe-working
    working_dir: /home/frappe
    command: >
      bash -c "
        echo '🔧 Initializing Frappe bench...' &&
        bench init --skip-redis-config-generation --frappe-branch version-15 frappe-bench &&
        cd frappe-bench &&
        echo '📦 Getting Flansa app...' &&
        bench get-app https://github.com/dineshvijayakumar2/flansa.git &&
        echo '⚙️ Configuring database and Redis...' &&
        bench set-config -g db_host mariadb &&
        bench set-config -g redis_cache redis://redis:6379 &&
        bench set-config -g redis_queue redis://redis:6379 &&
        bench set-config -g redis_socketio redis://redis:6379 &&
        echo '🏗️ Creating site...' &&
        bench new-site mysite.local --mariadb-root-password admin123 --admin-password admin123 --no-mariadb-socket &&
        echo '📱 Installing Flansa...' &&
        bench --site mysite.local install-app flansa &&
        echo '🏠 Setting homepage...' &&
        bench --site mysite.local set-config home_page 'app/flansa' &&
        bench --site mysite.local set-config default_workspace 'Flansa' &&
        echo '✅ Setup complete! Starting server...' &&
        bench serve --host 0.0.0.0 --port 8000
      "
    ports:
      - "8084:8000"
    depends_on:
      - mariadb
      - redis
    networks:
      - frappe-network
    volumes:
      - frappe_data:/home/frappe/frappe-bench

networks:
  frappe-network:

volumes:
  frappe_data: